"""Adds arts.owner column

Revision ID: dea2d165d130
Revises: 
Create Date: 2023-08-24 14:50:39.097268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dea2d165d130'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arts', sa.Column('owner', sa.String(), nullable=True))
    op.create_index(op.f('ix_arts_owner'), 'arts', ['owner'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_arts_owner'), table_name='arts')
    op.drop_column('arts', 'owner')
    # ### end Alembic commands ###
